
import FAQ from '@/components/FAQ'
import Hero from '@/components/heros/Hero'
import HomeCta from '@/components/HomeCTA'
import Services from '@/components/Services'
import Solution from '@/components/Solution'
import Testimonial from '@/components/Testimonial'
import Vision from '@/components/Vision'

export const metadata = {
  title: 'Fin Tech',
  description: 'Generated by StaticMania',
}
export default function Home() {
  return (
    <>
      <Hero />
      <Vision />
      <Services />
      <FAQ />
      <Solution />
      <Testimonial />
      <HomeCta />
    </>
  )
}
